config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  authenticated :user, ->(u) { u.admin? } do
    namespace :admin do
      root to: "dashboard#show"
    end
  end

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  namespace :api do
    namespace :v1 do
      get "health_check", to: "health_check#index"
    end
  end

  root "static#index"

  namespace :account do
    resource :password
  end

  resources :feeds
  resources :entries, only: :index, path: "outputs"

  resources :feeds do
    resource :update, only: :update, module: :feeds
  end

  resources :questions do
    resource :solve, only: :update, module: :questions
    resources :comments, module: :questions
    collection do
      post :search
    end
  end

  namespace :markdown do
    resource :preview, only: :create
  end

  resources :notifications, only: :index
  resources :integrations
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :notifications, through: :user, dependent: :destroy
  has_many :notification_mentions, through: :user, dependent: :destroy

  validates :title, :content, presence: true

  scope :by_keyword, ->(title) { where(arel_table[:title].matches("%#{sanitize_sql_like(title)}%")) }

  def solved?
    !solved_at.nil?
  end
end

app/controllers/questions/comments_controller.rb
class Questions::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:index, :new, :update, :create]
  before_action :set_comments, only: [:index, :create]
  before_action :set_comment, only: [:edit, :update]

  def index
    render "comments/index"
  end

  def new
    @comment = @question.comments.build(user: current_user)
    render "comments/new"
  end

  def edit
    render "comments/edit"
  end

  def create
    @comment = @question.comments.build(comment_params.merge(user: current_user))
    if @comment.save
      flash.now.notice = "コメントを投稿しました。"
      @new_comment = @question.comments.build(user: current_user)
      respond_to do |format|
        format.turbo_stream { render "comments/create" }
      end
    else
      render "comments/new"
    end
  end

  def update
    if @comment.update(comment_params)
      flash.now.notice = "コメントを編集しました。"
      respond_to do |format|
        format.turbo_stream { render "comments/update" }
      end
    else
      render "comments/edit"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_comments
    @comments = @question.comments.preload!(user: {avatar_attachment: :blob}).order(:created_at)
  end

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end
end

app/controllers/questions/solve_controller.rb
class Questions::SolveController < ApplicationController
  before_action :authenticate_user!

  def update
    @question = current_user.questions.find(params[:question_id])
    @question.update!(solved_at: Time.current)
    redirect_to question_path, notice: "質問を解決済みにしました"
  end
end

app/controllers/questions/solves_controller.rb
class Questions::SolvesController < ApplicationController
  before_action :authenticate_user!

  def update
    @question = current_user.questions.find(params[:question_id])
    @question.update!(solved_at: Time.current)
    redirect_to question_path(@question), notice: "質問を解決済みにしました"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update]

  def index
    @questions = Question.preload(:user, :comments).order(created_at: :desc)
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to questions_path, notice: "質問を投稿しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      redirect_to question_path, notice: "質問を編集しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def search
    @questions = Question.by_keyword(params[:title_search])
    respond_to do |format|
      format.turbo_stream do
        if @questions.count.zero?
          render turbo_stream: turbo_stream.update(:questions, partial: "questions/not_found")
        else
          render turbo_stream: turbo_stream.update(:questions, partial: "questions/question", collection: @questions)
        end
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def set_question
    @question = Question.find(params[:id])
    authorize @question
  end
end

app/helpers/question_helper.rb
module QuestionHelper
  def question_status_text(question)
    question.solved? ? "solved" : "unsolved"
  end

  def question_status_color(question)
    question.solved? ? "green-500" : "red-500"
  end
end

app/views/questions/_form.html.erb
<%= form_with(model: question, class: "p-4") do |form| %>
  <%= render "shared/error_messages", resource: question %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="md:grid md:grid-cols-2 md:gap-4" data-controller="markdown">
    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, id: "markdown_content", class: "h-[400px]",
        data: {
          controller: "markdown-upload",
          markdown_upload_url_value: rails_direct_uploads_url,
          markdown_target: "input",
          action: "input->markdown#preview drop->markdown-upload#dropUpload"
        } %>
      <p class="text-xs text-gray-700">マークダウン記法が使えます。<br>ドラック&ドロップで画像を挿入できます。</p>
    </div>

    <div>
      <div class="text-gray-700 text-sm font-bold mb-2">プレビュー</div>
      <div class="prose markdown_content shadow rounded h-[400px] p-2 overflow-y-auto" data-markdown-target="preview"></div>
    </div>
  </div>

  <div class="flex justify-end">
    <%= form.submit yield(:button_text), class: "btn btn-primary mt-4" %>
  </div>
<% end %>

app/views/questions/_not_found.html.erb
<div class="font-bold">
  質問が見つかりませんでした。
</div>
<p class="text-sm text-slate-500">別のキーワードで検索してください。</p>

app/views/questions/_question.html.erb
<div class="py-3 px-2 mb-2 shadow rounded">
  <div class="flex items-center gap-2 mb-2">
    <%= icon(question_status_text(question), css: "size-6 text-#{question_status_color(question)}") %>
    <div class="font-bold text-md">
      <%= link_to question.title, question_path(question), data: { turbo: false } %>
    </div>
  </div>
  <div class="flex items-center gap-2 ml-[32px]">
    <div class="flex items-center gap-2">
      <%= image_tag avatar_url_for(question.user), class: "shadow rounded-full w-6 h-6" %>
      <div class="text-xs font-bold">
        <%= question.user.name %>
      </div>
    </div>
    <div class="text-slate-500 text-xs flex items-center gap-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
      </svg>
      <%= question.created_at.to_date %>
    </div>
    <div class="flex items-center gap-1 text-slate-500 ml-2">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.76c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.076-4.076a1.526 1.526 0 0 1 1.037-.443 48.282 48.282 0 0 0 5.68-.494c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z" />
      </svg>
      <div class="text-sm">
        <%= question.comments.size %>
      </div>
    </div>
  </div>
</div>

app/views/questions/_search.html.erb
<%= form_with url: search_questions_path, method: :post, data: { controller: "debounce", debounce_target: "form" }, class: "flex justify-end" do |form| %>
  <div class="form-group w-[50%]">
    <%= form.search_field :title_search, placeholder: "キーワード検索", data: { action: "input->debounce#search" } %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<% provide(:button_text, "編集") %>

<h2 class="text-lg font-bold mb-8">
  なんでも質問
</h2>

<%= render "form", question: @question %>

app/views/questions/index.html.erb
<div class="mb-8 flex flex-col md:flex-row md:justify-between md:items-center">
  <div class="mb-2 md:mb-0">
    <h2 class="text-lg font-bold">
      なんでも質問
    </h2>
    <p class="text-sm text-slate-500">気軽に質問しましょう。</p>
  </div>
  <div class="flex justify-end">
    <%= link_to "質問する", new_question_path, class: "btn btn-primary" %>
  </div>
</div>

<%= render "search" %>

<%= turbo_frame_tag :questions do %>
  <%= render @questions %>
<% end %>

app/views/questions/new.html.erb
<% provide(:button_text, "投稿") %>

<h2 class="text-lg font-bold mb-8">
  なんでも質問
</h2>

<%= render "form", question: @question %>

app/views/questions/show.html.erb
<div class="py-2 px-4 shadow rounded mb-4">
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-1 mb-2">
      <%= icon(question_status_text(@question), css: "size-6 text-#{question_status_color(@question)}") %>
      <h2 class="text-lg font-bold">
        <%= @question.title %>
      </h2>
    </div>
    <% if current_user == @question.user %>
      <%= link_to edit_question_path(@question), class: "flex items-center gap-2" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
        </svg>
        <div class="font-bold">編集</div>
      <% end %>
    <% end %>
  </div>

  <div class="flex items-center gap-2 mb-8">
    <div class="flex items-center gap-2">
      <%= image_tag avatar_url_for(@question.user), class: "shadow rounded-full w-6 h-6" %>
      <div class="text-xs font-bold">
        <%= @question.user.name %>
      </div>
    </div>
    <div class="text-slate-500 text-xs flex items-center gap-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
      </svg>
      <%= @question.created_at.to_date %>
    </div>
  </div>

  <div class="prose markdown_content text-sm mb-2">
    <%= markdown(@question.content) %>
  </div>
  <div class="text-right">
    <%= button_to "解決済みにする", question_solve_path(@question), method: :put, class: "btn-sm btn-red", data: { turbo_confirm: "解決済みにしますか？" } if current_user == @question.user && !@question.solved? %>
  </div>
</div>

<%= turbo_frame_tag :comments, src: question_comments_path(@question) do %>
  <div className="flex justify-center" aria-label="読み込み中">
    <div className="animate-spin h-10 w-10 border-4 border-blue-500 rounded-full border-t-transparent"></div>
  </div>
<% end %>
<%= turbo_frame_tag :new_comment_frame, src: new_question_comment_path(@question) %>