config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  authenticated :user, ->(u) { u.admin? } do
    namespace :admin do
      root to: "dashboard#show"
    end
  end

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  namespace :api do
    namespace :v1 do
      get "health_check", to: "health_check#index"
    end
  end

  root "static#index"

  namespace :account do
    resource :password
  end

  resources :feeds
  resources :entries, only: :index, path: "outputs"

  resources :feeds do
    resource :update, only: :update, module: :feeds
  end

  resources :questions do
    resource :solve, only: :update, module: :questions
    resources :comments, module: :questions
    collection do
      post :search
    end
  end

  namespace :markdown do
    resource :preview, only: :create
  end

  resources :notifications, only: :index
  resources :integrations
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def show
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @entries = Entry.preload(feed: :user).order(published_at: :desc).limit(5)
    @questions = Question.preload(:user).order(created_at: :desc).limit(5)
  end
end

app/views/dashboard/show.html.erb
<div class="flex flex-col gap-4">
  <div class="shadow p-4 rounded-sm">
    学習時間とかのグラフ入れたい
  </div>

  <div class="grid sm:grid-cols-2 gap-4">
    <div class="shadow p-4 rounded-sm">
      <div class="font-bold mb-2">新着アウトプット</div>
      <%= render @entries %>
      <div class="flex justify-end items-center">
        <%= link_to entries_path, class: "text-sm font-bold flex items-center gap-1" do %>
          <div>もっと見る</div>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
          </svg>
        <% end %>
      </div>
    </div>
    <div class="shadow p-4 rounded-sm">
      <div class="font-bold mb-2">新着なんでも質問</div>
      <%= render @questions %>
      <div class="flex justify-end items-center">
        <%= link_to questions_path, class: "text-sm font-bold flex items-center gap-1" do %>
          <div>もっと見る</div>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</div>