config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  authenticated :user, ->(u) { u.admin? } do
    namespace :admin do
      root to: "dashboard#show"
    end
  end

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  namespace :api do
    namespace :v1 do
      get "health_check", to: "health_check#index"
    end
  end

  root "static#index"

  namespace :account do
    resource :password
  end

  resources :feeds
  resources :entries, only: :index, path: "outputs"

  resources :feeds do
    resource :update, only: :update, module: :feeds
  end

  resources :questions do
    resource :solve, only: :update, module: :questions
    resources :comments, module: :questions
    collection do
      post :search
    end
  end

  namespace :markdown do
    resource :preview, only: :create
  end

  resources :notifications, only: :index
  resources :integrations
end

app/models/feed.rb
class Feed < ApplicationRecord
  validates :title, :url, presence: true
  validates :url, uniqueness: true

  belongs_to :user
  has_many :entries, dependent: :destroy
end

app/controllers/feeds/updates_controller.rb
class Feeds::UpdatesController < ApplicationController
  before_action :authenticate_user!

  def update
    feed = current_user.feeds.find(params[:feed_id])
    FetchEntriesJob.perform_async(feed.id)
    redirect_to feeds_path, notice: "フィードを更新しました"
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :authenticate_user!

  def index
    @feeds = current_user.feeds.order(created_at: :desc)
  end

  def new
    @feed = Feed.new
  end

  def create
    response = fetch_feed(feed_params[:url])
    return unless response.is_a?(Faraday::Response)

    feed = Feedjira.parse(response.body)
    title = feed.title
    @feed = current_user.feeds.new(feed_params.merge(title: title))

    if @feed.save
      redirect_to feeds_path, notice: "フィードを登録しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy!

    redirect_to feeds_path, notice: "フィードを解除しました。"
  end

  private

  def fetch_feed(url)
    Faraday.get(url)
  rescue Faraday::ConnectionFailed
    flash[:alert] = "フィードの取得に失敗しました。"
    render :new, status: :unprocessable_entity
  end

  def feed_params
    params.require(:feed).permit(:url)
  end
end

app/views/feeds/_feed.html.erb
<div class="md:flex md:justify-between md:items-end mb-4 pb-2 border-b">
  <div>
    <div class="font-bold">
      <%= feed.title %>
    </div>
    <%= link_to feed.url, feed.url, class: "text-sm" %>
  </div>
  <div class="md:flex md:items-end md:justify-end md:gap-4">
    <div class="flex items-center gap-1 text-xs">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
      </svg>
      <%= l(feed.updated_at.to_time, format: :long) %>
    </div>
    <div class="flex items-center justify-end gap-2">
      <%= button_to "更新", feed_update_path(feed), method: :put, class: "btn-sm btn-primary-outline" %>
      <%= button_to "解除", feed_path(feed), method: :delete, class: "btn-sm btn-red", data: { turbo_confirm: "解除しますか？" } %>
    </div>
  </div>
</div>

app/views/feeds/index.html.erb
<%= content_for :settings_block do %>
  <h2 class="font-bold text-lg">RSSフィード<h2>
  <p class="text-xs text-slate-500 mb-4">登録後「更新」ボタンを押すことで記事を取得できます。</p>

  <% if @feeds.empty? %>
    <div class="text-slate-400 text-sm">登録中のRSSフィードはありません。</div>
  <% else %>
    <div>
      <%= render @feeds %>
    </div>
  <% end %>
  <div class="flex justify-end">
    <%= link_to "登録する", new_feed_path, class: "btn btn-primary" %>
  </div>
<% end %>

<%= render "shared/settings_block" %>

app/views/feeds/new.html.erb
<%= content_for :settings_block do %>
  <h2 class="font-bold text-lg mb-4">RSSフィード<h2>

  <%= form_with(model: @feed, html: { class: "p-4" }) do |form| %>
    <div class="form-group">
      <%= form.label :url %>
      <%= form.text_field :url %>
    </div>

    <% if @feed.present? %>
      <%= render "shared/error_messages", resource: @feed %>
    <% end %>

    <div class="flex justify-end">
      <%= form.submit "登録", class: "btn btn-primary mt-4" %>
    </div>
  <% end %>
<% end %>

<%= render "shared/settings_block" %>