config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  authenticated :user, ->(u) { u.admin? } do
    namespace :admin do
      root to: "dashboard#show"
    end
  end

  authenticated :user do
    root to: "dashboard#show", as: :user_root
  end

  namespace :api do
    namespace :v1 do
      get "health_check", to: "health_check#index"
    end
  end

  root "static#index"

  namespace :account do
    resource :password
  end

  resources :feeds
  resources :entries, only: :index, path: "outputs"

  resources :feeds do
    resource :update, only: :update, module: :feeds
  end

  resources :questions do
    resource :solve, only: :update, module: :questions
    resources :comments, module: :questions
    collection do
      post :search
    end
  end

  namespace :markdown do
    resource :preview, only: :create
  end

  resources :notifications, only: :index
  resources :integrations
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class="text-sm text-red-500"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div
    data-controller="notification"
    data-notification-delay-value="5000"
    class="transition transform duration-1000 hidden fixed top-10 right-5 inline-flex items-center gap-2 <%= flash_color(key) %> shadow py-2 px-4 text-sm font-bold text-gray-600 rounded"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 rounded-full">
      <path stroke-linecap="round" stroke-linejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
    </svg>
    <%= value %>
    <button data-action="notification#hide">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5 text-gray-500">
        <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
      </svg>
    </button>
  </div>
<% end %>

app/views/shared/_settings_block.html.erb
<div class="flex shadow">
  <div class="p-4 border-r md:w-64">
    <div class="text-sm text-slate-400 font-bold md:px-4 mb-2 text-center md:text-left">設定</div>
    <ul>
      <li class="mb-1">
        <%= link_to edit_user_registration_path, class: "#{controller.controller_path == "users/registrations" ? "bg-gray-200" : ""} text-sm text-slate-500 flex items-center gap-2 px-4 py-2 rounded-sm hover:bg-gray-200 w-full" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
          </svg>
          <div class="hidden md:block">プロフィール</div>
        <% end %>
      </li>
      <li class="mb-1">
        <%= link_to feeds_path, class: "#{controller.controller_path == "feeds" ? "bg-gray-200" : ""} text-sm text-slate-500 flex items-center gap-2 px-4 py-2  rounded-sm hover:bg-gray-200 w-full" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12.75 19.5v-.75a7.5 7.5 0 0 0-7.5-7.5H4.5m0-6.75h.75c7.87 0 14.25 6.38 14.25 14.25v.75M6 18.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
          </svg>
          <div class="hidden md:block">RSSフィード</div>
        <% end %>
      </li>
      <li class="mb-1">
        <%= link_to account_password_path, class: "#{controller.controller_path == "account/passwords" ? "bg-gray-200" : ""} text-sm text-slate-500 flex items-center gap-2 px-4 py-2  rounded-sm hover:bg-gray-200 w-full" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 1 0-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 0 0 2.25-2.25v-6.75a2.25 2.25 0 0 0-2.25-2.25H6.75a2.25 2.25 0 0 0-2.25 2.25v6.75a2.25 2.25 0 0 0 2.25 2.25Z" />
          </svg>
          <div class="hidden md:block">パスワード</div>
        <% end %>
      </li>
      <li class="mb-1">
        <%= link_to integrations_path, class: "#{controller.controller_path == "integrations" ? "bg-gray-200" : ""} text-sm text-slate-500 flex items-center gap-2 px-4 py-2  rounded-sm hover:bg-gray-200 w-full" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M11.42 15.17 17.25 21A2.652 2.652 0 0 0 21 17.25l-5.877-5.877M11.42 15.17l2.496-3.03c.317-.384.74-.626 1.208-.766M11.42 15.17l-4.655 5.653a2.548 2.548 0 1 1-3.586-3.586l6.837-5.63m5.108-.233c.55-.164 1.163-.188 1.743-.14a4.5 4.5 0 0 0 4.486-6.336l-3.276 3.277a3.004 3.004 0 0 1-2.25-2.25l3.276-3.276a4.5 4.5 0 0 0-6.336 4.486c.091 1.076-.071 2.264-.904 2.95l-.102.085m-1.745 1.437L5.909 7.5H4.5L2.25 3.75l1.5-1.5L7.5 4.5v1.409l4.26 4.26m-1.745 1.437 1.745-1.437m6.615 8.206L15.75 15.75M4.867 19.125h.008v.008h-.008v-.008Z" />
          </svg>
          <div class="hidden md:block">外部ツール連携</div>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="p-4 grow">
    <%= yield :settings_block %>
  </div>
</div>